### ISSUE TITLE
[Motivation] Elaborate RDM Success story

### ISSUE THREAD

**Issue by CaptainSifff** [DE-RSE/2023_paper-RSE-groups#15]

**Comment by CaptainSifff** [comment]
adding a reference would be a start. e.g. a growth story of a Länder-Initiative.

**Comment by CaptainSifff** [comment]
NFDI?

**Comment by CaptainSifff** [comment]
Data Stewards?

**Comment by CaptainSifff** [comment]
RfII?

**Comment by CaptainSifff** [comment]
https://orcid.org/0000-0002-0121-9261

**Comment by jlinx** [comment]
> Data Stewards?

I kind of have mixed feelings here. There are a lot of people out there who have the role of a "Data Steward" in addition to their daily work. Still, there are also dedicated positions for Data Stewards. I see similarities to RSEs. Nowadays we are in a similar situation where we have both, dedicated positions AND RSEs who wear multiple hats but get mostly paid for their non RSE work...

**Comment by jlinx** [comment]
> NFDI?

yes, definitly

**Comment by jlinx** [comment]
Once [merge request #54](https://github.com/DE-RSE/2023_paper-RSE-groups/pull/54) is merged, I think this issue could be closed.
