### ISSUE TITLE
Double-check definition of research software in the introduction

### ISSUE THREAD

**Issue by dokempf** [DE-RSE/2023_paper-RSE-groups#2]
From GoogleDoc by Andreas Wagner:
I tried to find it in this paper and in the mentioned "Defining Research Software", but it seems to be only mentioned in passing or implicitly, maybe it's worth a footnote?: Models in the sense of neural network weights are maybe in-between research data and research software (they can transform input to output in a meaningful way analogous to algorithms, I suppose they would also satisfy some definition of (non-software) research data, although I can't find one at present). In my opinion, the RSE definition of software should cover them, too. And I don't think it does (yet), relying on "Source Code, Algorithms, Scripts, Workflows and Executables"... It's difficult not to evoke the impression that we want to jump on the latest AI hype; at the same time, I think it's obvious that the AI developments have and will have important consequences for (the relevance of) the quality standards, best practices and ethics of research software engineering.

Dominic: If the quote is indeed not an actual quote that needs to be fixed. We could also extend the definition of RS, but we should always refer to existing definitions, as coming up with our own is not in the scope of this paper.

**Comment by awagner-mainz** [comment]
To clarify: I did not mean to say that the definition is not an actual quote. What I did mean was that neither the definition nor any other passage in this paper and in the quoted paper explicitly mention neural networks and models, and in some passages, like the quoted one, they seem not to be covered at all. They could probably be understood to be intended implicitly, but I thought it could be worthwhile mentioning them explicitly, perhaps in a footnote.

**Comment by CaptainSifff** [comment]
broad definition from the other paper:

> **Software**: Source code, documentation, tests, executables
> and all other artefacts that are created by humans during the development process
> that are necessary to understand its purpose.
> 
> **Research software**: Foundational algorithms, the software itself,
> as well as scripts and computational workflows that were created
> during the research process or for a research purpose, across all domains of research.
> This definition is broader than in @FAIR4RS and is the outcome of a recent
> discussion in @Gruenpeter2021.
> 
> **Research software engineers**: People who
> create or improve research software and/or the structures that the software interacts with
> in the computational ecosystem of a research domain.
> They are highly skilled team members who may also choose to conduct their own research as
> part of their role.
> However, we also recognise that many RSEs have chosen specifically to focus on a technical
> role as an alternative to a traditional research role because they enjoy and wish to focus
> on the development of research software.
>

**Comment by knarrff** [comment]
My 2 cents to AI models: if "they can transform input to output in a meaningful way analogous to algorithms", then they should be considered algorithms and fall under the definition anyway. They fact that they are "just" numbers with a given structure and a "runtime system" to interpret them while the model is "run" shows the similarity to software, which is "just" numbers with a given structure and a "runtime system" to interpret them while running the software. What part of an AI model is the "software" and what part is "just data" the software processes is a discussion that is likely long, opinionated and imho not really worth having other than for fun - and we should avoid it in the paper.

**Comment by CaptainSifff** [comment]
hasn't this been merged in the meantime by this: https://github.com/DE-RSE/2023_paper-RSE-groups/pull/13
