### ISSUE TITLE
Mention synergies with existing HPC structures

### ISSUE THREAD

**Issue by dokempf** [DE-RSE/2023_paper-RSE-groups#33]
HPC (High Performance Computing) is an RSE-related field that is (partly due to its nature) typically quite structured on all levels (local, network, state, national) and provides a lot of training and funding opportunities. We currently lack mentionings of synergies with these structures when establishing an RSE department in the paper. As an example @CaptainSifff mentioned the bavarian HPC network, that allows you to apply for funding for a basis project to "establish central contact partners for HPC questions".

This can e.g. be done in the "network of institutional partners", the "teaching activities" or in the "funding" sections.

**Comment by dokempf** [comment]
Link for the example: https://www.konwihr.de/how-to-apply/

**Comment by CaptainSifff** [comment]
shameless ad: https://www.konwihr.de/konwihr-projects/basis-project-university-of-wurzburg/
