### ISSUE TITLE
workshop feedback on the structure

### ISSUE THREAD

**Issue by CaptainSifff** [DE-RSE/2023_paper-RSE-groups#44]
some feedback by the DFG representative
- Modulbeschreibung: Vorschlag immer gleiche Struktur je Modul (subsection), also bspw. "Beschreibung" (4-5 Sätze; "was ist gemeint mit der Überschrift"), "Benefits for institution" (3-4 Sätze; "mögliche Benefits, wie profitiert die Einrichtung", "multiple, positive effects"), "Beispiel" (2-3 Sätze; "Success Story" oder weniger wünschenswert fiktives Beispiel)

- Hinweis auf diese WR-Publikation: 
- https://www.wissenschaftsrat.de/download/2023/1580-23.pdf?__blob=publicationFile&v=11 
einfach nach "Software suchen" (S. 50 zB und natürlich der letzte Absatz)

**Comment by berndflemisch** [comment]
I read through all module descriptions. They have very different lengths which, in my understanding, is ok in principle. Especially the longer ones might profit from being more concise and eventually being reshuffled a bit towards a more harmonised structure. I'll go ahead with this.

**Comment by dokempf** [comment]
My understand is that Bernds changes in #60 work towards this issue, but we decided to not fully harmonize the structure.
