### ISSUE TITLE
programmpauschale

### ISSUE THREAD

**Issue by CaptainSifff** [DE-RSE/2023_paper-RSE-groups#45]
Some other feedback:
wir hatten in Jena bzw. jetzt in Würzburg dazu gesprochen, ob die DFG-Programmpauschale (PP) dazu genutzt werden kann, RSE-Pools (mit) zu finanzieren. 

Ich habe eine Gelegenheit genutzt, um dies mit der Leitung der Gruppe Finanzen anzusprechen. Knapp ausgedrückt: Die PP-Leitlinie eurer Uni/Hochschule regelt, wie die PP ausgegeben wird. Sowie die PP bei der Uni/Hochschule eingeht, ist sie Teil des allgemeinen Haushalts. Als Pauschale muss die PP eben pauschal, z. B. „der Forschung“ zugutekommen. Eine genaue Verrechnung mit Projekten darf nicht stattfinden. Aber diese Argumentation ist ja auch nicht angedacht, wie ich das Papier lese. Paraphrasiert wurde mir gesagt: Nicht die PP würde eine Organisationseinheit bezahlen, sondern die PP entlastet bei den allgemeinen Ausgaben zur Unterstützung der Forschung in der Uni/Hochschule.
In Zeile 514 kommt dies ja auch schön zur Sprache.

**Comment by dokempf** [comment]
We discussed this today and we came to conclusion that our current writing is in line with this (without being too specific or verbose).
