### ISSUE TITLE
Collect affiliation data

### ISSUE THREAD

**Issue by dokempf** [DE-RSE/2023_paper-RSE-groups#46]
Potentially in a data file (YAML or similar) and feed it into the paper.

**Comment by jngrad** [comment]
Something similar was done in CaptainSifff/paper_teaching-learning-RSE: [contributors.yml](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/contributors.yml) and [filter.py](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/filter.py).
