### ISSUE TITLE
RSE department/team/hub/...?

### ISSUE THREAD

**Issue by pancetta** [DE-RSE/2023_paper-RSE-groups#48]
Do we want to talk about an "RSE department", a "central RSE team" or an "RSE hub", consistently throughout the paper? The term "department" is not necessarily understood the same way for everyone: what is a department at a university, what is a department at a research center? And internationally speaking, a US-style department can be rather large (100+ people, "divisions" are smaller). A "team" or, more preferable, "hub" can be of any size and is not bound to the administrative understanding of a department. A hub would also include virtual teams, which is not the case for a department.

**Comment by pancetta** [comment]
After discussion briefly with @dokempf, I'll try to add something along these lines to the motivation.

**Comment by pancetta** [comment]
See also #57

**Comment by pancetta** [comment]
Decision: talk about "RSE unit", see

**Comment by jlinx** [comment]
> Decision: talk about "RSE unit", see #62

In the title we will speak of a "central RSE unit"

**Comment by dokempf** [comment]
Superseded by #63.
