### ISSUE TITLE
"decentralized RSEs" or "spokes"?

### ISSUE THREAD

**Issue by berndflemisch** [DE-RSE/2023_paper-RSE-groups#57]
The vision section is full of "decentralized RSEs", much more than "spokes". Should we unify this? In my memory, we agreed on "spokes". Or are spokes more the organizational entities than the persons?

**Comment by pancetta** [comment]
I'd strongly vote for "spokes", esp. if we settle for the "RSE Hub" in the text. Spokes can be individuals or teams or units.
