### ISSUE TITLE
Reference resources for software management plans

### ISSUE THREAD

**Issue by dokempf** [DE-RSE/2023_paper-RSE-groups#6]
Andreas Wagner on Google Docs:
The DFG's GWP guidelines seem to have transitioned to a webapp now: [https://wissenschaftliche-integritaet.de/en/](https://www.google.com/url?q=https://wissenschaftliche-integritaet.de/en/&sa=D&source=docs&ust=1706088311835453&usg=AOvVaw2G_M_cUhkcIdQ2nRHGLTvb) ; it has a manually curated "keyword index" with "research software" listing 24 resulting comments and passages: [https://wissenschaftliche-integritaet.de/en/comment-tags/research-software/](https://www.google.com/url?q=https://wissenschaftliche-integritaet.de/en/comment-tags/research-software/&sa=D&source=docs&ust=1706088311835553&usg=AOvVaw2noOnBuTofGFOvic9qWPzA) . As another example of a research organizations' backing of RSM, you could mention Max Planck Digital Library's inclusion of a software management plan template in its RDMO instance: [https://rdm.mpdl.mpg.de/2022/12/09/smp-template-available/](https://www.google.com/url?q=https://rdm.mpdl.mpg.de/2022/12/09/smp-template-available/&sa=D&source=docs&ust=1706088311835595&usg=AOvVaw0sGSelwVMHASN0kM4UeW-_)

This is in the benefits subsection of the motivation section.

**Comment by astruck** [comment]
We already cite DFG GWP and that discussion of RDM and RSE are required. I acknowledge that the MPDL as a central group for MPG has put effort in creating the SMP template for the tool RDMO. (Such a template has been available for years in another tool DMPonline.) I argue that referencing their work on the template does not support our cause for establishing RSE hubs (although a SMP may benefit from consulting services). Closing.
